// SPDX-License-Identifier: Apache-2.0
// Copyright (C) 2026 The Falco Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

package schema

// Priority represents a Falco rule priority level.
// Priority determines the severity of alerts generated by rules.
type Priority string

// Falco priority level constants (ordered from highest to lowest severity).
const (
	// PriorityEmergency indicates system is unusable (highest severity).
	PriorityEmergency Priority = "EMERGENCY"

	// PriorityAlert indicates action must be taken immediately.
	PriorityAlert Priority = "ALERT"

	// PriorityCritical indicates critical conditions.
	PriorityCritical Priority = "CRITICAL"

	// PriorityError indicates error conditions.
	PriorityError Priority = "ERROR"

	// PriorityWarning indicates warning conditions (recommended default).
	PriorityWarning Priority = "WARNING"

	// PriorityNotice indicates normal but significant condition.
	PriorityNotice Priority = "NOTICE"

	// PriorityInformational indicates informational messages.
	PriorityInformational Priority = "INFORMATIONAL"

	// PriorityDebug indicates debug-level messages (lowest severity).
	PriorityDebug Priority = "DEBUG"
)

// String returns the string representation of the priority.
func (p Priority) String() string {
	return string(p)
}

// PriorityInfo contains metadata about a priority level.
type PriorityInfo struct {
	Level       Priority
	Description string
	Severity    int // Numeric severity (0 = highest, 7 = lowest)
}

// DefaultPriority is the recommended default priority for new rules.
const DefaultPriority = PriorityWarning

// AllPriorities returns all priority levels with their descriptions.
// Ordered from highest to lowest severity.
var AllPriorities = []PriorityInfo{
	{PriorityEmergency, "System is unusable (highest severity)", 0},
	{PriorityAlert, "Action must be taken immediately", 1},
	{PriorityCritical, "Critical conditions", 2},
	{PriorityError, "Error conditions", 3},
	{PriorityWarning, "Warning conditions (recommended default)", 4},
	{PriorityNotice, "Normal but significant condition", 5},
	{PriorityInformational, "Informational messages", 6},
	{PriorityDebug, "Debug-level messages (lowest severity)", 7},
}

// prioritySet is a fast lookup set for valid priorities.
var prioritySet = func() map[Priority]struct{} {
	m := make(map[Priority]struct{}, len(AllPriorities))
	for _, p := range AllPriorities {
		m[p.Level] = struct{}{}
	}
	return m
}()

// IsValidPriority checks if the given string is a valid priority level.
func IsValidPriority(p string) bool {
	_, ok := prioritySet[Priority(p)]
	return ok
}
